#! /usr/bin/env ruby

gem 'rails', '>= 3', '< 4'
require 'rails'
require 'active_model'

require 'pry'

require_relative '../lib/mongoid-grid_fs.rb'

Mongoid.configure do |config|
  config.connect_to('mongoid-grid_fs_test')
end

require 'irb'

$FUCKING_HACK = IRB.method(:load_modules)

def IRB.load_modules
  $FUCKING_HACK.call

  prompt = 'mongoid_grid_fs'

  IRB.conf[:PROMPT][:RO] = {
    PROMPT_I: "#{prompt}:%03n:%i> ",
    PROMPT_N: "#{prompt}:%03n:%i> ",
    PROMPT_S: "#{prompt}:%03n:%i%l ",
    PROMPT_C: "#{prompt}:%03n:%i* ",
    RETURN: "=> %s\n"
  }

  IRB.conf[:PROMPT_MODE] = :RO
  IRB.conf[:AUTO_INDENT] = true
end

module ::Kernel
  def grid_fs
    Mongoid::GridFs
  end
end

ARGV.clear

::IRB.start
